### ISSUE TITLE
New feature in new FW

### ISSUE THREAD

**Issue by Kabron287** [Renstec/LD2410#1]
Hello,
wonderful lib and example!

Now. new FW is available with ambient light sensor activated.
https://www.pgyer.com/Lq8p?spm=a2g2w.detail.0.1.6b3b1e4cammVlk

Would you be kind to add light sensor support.
Thanks in advance,
Vladimir 
![Screenshot_2023-02-12-12-15-10-680_com example hlkradartool](https://user-images.githubusercontent.com/2493191/218303117-2848fdef-e506-498e-843f-6ecf564916da.jpg)

**Comment by Renstec** [comment]
Thank you for liking the library.

At the moment I can't find an English datasheet with the current communication protocol for the light sensor.
So I close this issue for now, but if I find a datasheet I will of course implement the light sensor. 

Thanks a lot

**Comment by Kabron287** [comment]
Hi there again.
I found where ambient intensity transferred.
It is the 34th byte in the data field.

![Data](https://user-images.githubusercontent.com/2493191/235608340-a96bc440-eb14-435b-a598-2ace4fe3c6b0.jpg)

**Comment by Kabron287** [comment]
Sorry, actually it is 31th byte. 
I do not realize what are the other changes in data arrangement, but 
if I highlight sensor with modulated beam, byte 31 changed correspondingly.

**Comment by Renstec** [comment]
Hello Kabron287,

I wanted to let you know that I do not support the LD2410/B/C module in my library. 
I apologize for any inconvenience this may cause you. 

Please note that I do not have the necessary hardware to test the B/C module and ensure its compatibility with my library.

It's worth noting that the Light Sensor is only supported on the LD2410/B/C, while my library only supports the Serial Protocol for the LD2410 module. 

If you wish to implement the light sensor, you can find the partly data-sheet for the  module on GitHub at the following link: https://github.com/esphome/feature-requests/issues/2156.


If you have any further questions or concerns, please don't hesitate to reach out to me.

Best regards,
Renstec
